### ISSUE TITLE
Add colours to CLI ouput

### ISSUE THREAD

**Issue by fr4nkln11** [TechWiz-3/happy-jar-cli#13]
I would like to modify the codebase by adding color to CLI prompts, like error messages and successful entry prompts.
I think it would give the CLI  a nice look to it.

I would like to personally take on this issue, its in fact my first issue on github 😄

**Comment by fr4nkln11** [comment]
Hi @TechWiz-3, is this a good contribution to work on? I've been waiting for a reply from you to get started

**Comment by TechWiz-3** [comment]
Hey man apologies for taking so long to respond, I was busy preparing for an exam and my github notifications were going off like crazy.
Yeah, I definitely like this, however it should only be optional so let's have a `--color` option to use color.

Also as specified in the PR, please use [`rich`](https://rich.readthedocs.io/en/stable/console.html#printing).  Styling should be easy in that case, `console.print("whatever text", style=success/error)` and the variables `success` and `error` can be set to `None` if  `--color` is not used.

Hope that makes sense 🙏

**Comment by fr4nkln11** [comment]
Okay, I'll use `rich`, does this mean I'll have to create a new PR? and also can you assign me to this issue?

**Comment by TechWiz-3** [comment]
If you're happy to, you can edit your current PR, no problem 👍

**Comment by fr4nkln11** [comment]
About making the colors optional, i have tiny problem with that, I can understand color option for display entry, but how is the user supposed to choose whether or not error / success output is colored.
I think in most CLI apps, colors for important prompts are default and none changeable too I guess, I can still add the `--color` option for displaying entries but I'll leave errors and success to have default colors.

**Comment by TechWiz-3** [comment]
That makes sense 👍

**Comment by fr4nkln11** [comment]
Great, I'll get to it
