### ISSUE TITLE
No entries!

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/happy-jar-cli#14]
If no entries, print "No entries for selected time period!"

**Comment by Karthik-PM** [comment]
so basically if i give happy get all , if there are no entries i have to give "No entries for selected time period!" right?

**Comment by TechWiz-3** [comment]
Nah this for `happy get <date>` `happy get today` and `happy get [before|after] today/<date>` variations.

When you specify a time period but there are no logs for that period

**Comment by Karthik-PM** [comment]
ohh alright ! so like this right
![image](https://user-images.githubusercontent.com/72903849/193451431-1d11b038-377a-4f4a-ad20-94a4d79283ba.png)

**Comment by Karthik-PM** [comment]
![image](https://user-images.githubusercontent.com/72903849/193451649-7072cf39-4b96-4ada-a667-2769349f9a1c.png)

**Comment by Karthik-PM** [comment]
i have created a PR for happy get <date>  and happy get today
