### ISSUE TITLE
Change flower output

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/happy-jar-cli#23]
Currently the `random.choice()` method is used to get a flower for each entry in the `--flowers` option. Sometimes flowers can be duplicated a lot in the entries as shown below.

![2022-10-05 15_24_41](https://user-images.githubusercontent.com/75515581/193981150-d88481ec-0562-4645-94ce-4da89a177c55.png)

Edit the `display_entry()` function to make sure that flowers are never repeated consecutively.

**Comment by redromnon** [comment]
Hi there! I'm willing to try and fix this issue. Please assgin this.

**Comment by Harshil-Jani** [comment]
Hi ! I would like to take this up.

**Comment by TechWiz-3** [comment]
Sure 👍 
Also I'm curious, how did you find this repo?

**Comment by redromnon** [comment]
I came across this repo while scrolling through GitHub's Issue section to find Python projects.
