### ISSUE TITLE
Add feature to optionally tag entries while logging and then retrieve entries by tag

### ISSUE THREAD

**Issue by N-Shar-ma** [TechWiz-3/happy-jar-cli#28]
I feel that regular frequent users of the CLI might have different kind of happy thoughts they log and might like to retrieve certain types of entries. For example, a user might regularly record happy thoughts of mainly 3 kinds: career achievements, personal milestones and random thoughts. 

In this case a command like `happy log "I got a job at my dream company" --tag career-achievement` might be helpful. And a command like `happy get all --tag career-achievement` can be used to retrieve entries with a certain tag.

A future enhancement can be adding support for a new command like `happy tags` which lists all the tags used so far. This command can be a nice way to 1st check all tags used so far and then view entries of a certain tag from that list.

If this sounds good, I'd like to try my hand at adding this feature! :)

**Comment by TechWiz-3** [comment]
I like this man ❤️ go ahead

**Comment by TechWiz-3** [comment]
Relevant issue: #30
