### ISSUE TITLE
Github Actions: automated update to pypi

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/happy-jar-cli#3]
Workflow run on manually (`workflow_dispatch`). 

https://dev.to/iamtekson/publish-package-to-pypi-and-release-new-version-using-github-actions-108k

**Comment by hitblast** [comment]
I'll work on this issue in my development fork. I think we had a chat on Discord about the same issue a while ago. You can assign me on this issue :D

**Comment by TechWiz-3** [comment]
Sure thing lol

I turned both of the things we talked about into issues (pypi update and other package managers)

**Comment by hitblast** [comment]
I guess now it might be a good time to close it.

**Comment by TechWiz-3** [comment]
Yezzir, thank you
