### ISSUE TITLE
Add new command `happy get tags` to view list of all tags used yet

### ISSUE THREAD

**Issue by N-Shar-ma** [TechWiz-3/happy-jar-cli#34]
As discussed in #28:

> A future enhancement can be adding support for a new command like happy tags which lists all the tags used so far. This command can be a nice way to 1st check all tags used so far and then view entries of a certain tag from that list.

I'd like to add this command now that the basic tagging feature is ready!

**Comment by TechWiz-3** [comment]
Go ahead 👍 

Just be aware of #30 as there may be changes while you're working on the PR
