### ISSUE TITLE
Use `click` in place of `argparse`, and implementing MVC

### ISSUE THREAD

**Issue by fr4nkln11** [TechWiz-3/happy-jar-cli#35]
This is just a suggestion, we could try using `click` to build our CLI, instead of the default `argparse` module.
There is a chance that it might be easier to maintain for new contributors, and we could probably try an MVC model for the app.

**Comment by fr4nkln11** [comment]
And, maybe its finally time to use @diwash007 's setup in #10 .
It could help out with the MVC, if it could be modified a little bit

**Comment by TechWiz-3** [comment]
> Re click: personally i've never used click but am open to trying it out, as long as it's functional and simple enough to understand i won't object

> Re refactoring: i messaged diwash a number of days ago to see if he would like to update the PR as we are ready to implement the structure (now that poetry is setup), however he hasn't done anything yet, i think i might implement it myself if he doesn't want to

**Comment by fr4nkln11** [comment]
Well, me neither, but I just thought it could be a good way to learn new stuff with this project

**Comment by TechWiz-3** [comment]
Any particular reason you'd like to learn Click over other argument parsers like docopt or Typer?

**Comment by diwash007** [comment]
I have been quite busy lately ... You may go ahead with refactoring

**Comment by TechWiz-3** [comment]
Oki, thanks for letting us know 👍

**Comment by fr4nkln11** [comment]
> Any particular reason you'd like to learn Click over other argument parsers like docopt or Typer?

I used it recently on another open source project, so I was wondering if it could work here.
It would be a bit difficult to replicate some of the stuff you did here with `argparse` in `click`, and now that I think about it would be an unnecessary change.
I'm just going to try it in a different branch on my fork, for educational purposes.
