### ISSUE TITLE
Bug when displaying emojis for a tagged entry

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/happy-jar-cli#38]
# Bug

## Steps to reproduce
<img width="532" alt="Screen Shot 2022-10-23 at 11 17 35 am" src="https://user-images.githubusercontent.com/75515581/197367151-748389e7-b6e6-4e32-a495-d8292a51bafb.png">

## Info

> This screenshot shows that the entry is being stored correctly in the jar, which means the issue occurs when displaying the entry

<img width="806" alt="Screen Shot 2022-10-23 at 11 17 52 am" src="https://user-images.githubusercontent.com/75515581/197367153-c1917ba7-d4c2-4d2e-b10d-3d4e6e06c1f4.png">

> Using the released version also has this issue when a `#tag` is placed in front of the emoji.

> These screenshots show how adding the `#tag` affects how the entry is displayed for `happy get today`

<img width="559" alt="Screen Shot 2022-10-23 at 11 21 49 am" src="https://user-images.githubusercontent.com/75515581/197367257-2b84a203-3446-4485-9b56-f87d4ce410eb.png">

<img width="447" alt="Screen Shot 2022-10-23 at 11 21 55 am" src="https://user-images.githubusercontent.com/75515581/197367260-56c0591c-ff77-4d7c-911c-8151b68da1a7.png">

**Comment by TechWiz-3** [comment]
[`L224`](https://github.com/TechWiz-3/happy-jar-cli/blob/main/happy/main.py#L224)

**Comment by N-Shar-ma** [comment]
I'd noticed the potential for this bug while making my last PR but it had then slipped my mind 😬

I'd love to fix this!

**Comment by TechWiz-3** [comment]
Sure go ahead 👍
