### ISSUE TITLE
Support getting after and before dates

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/happy-jar-cli#4]
Currently the argument after the subcommand `happy get [all|today|dd/mm/yy]` can be `all`, `today` or `dd/mm/yy`.

Add another two, which are `until` and `before`.

`until` gets all entries until a date, then breaks.
`before` gets all entries before a date, then breaks.

**Example usage:**
`happy get until 09/09/2022`
`happy get before 01/01/2022`

**Above and beyond**
If you would like to, the following work would also be really appreciated:
* support for the `--flowers` option
* also support `happy get [before|until] today`

**Important note:**
Because of the way the argparsing and help command is setup, to check if these options are being used you will need to use `if args.all == "until or before"`.
This is because whatever argument comes after `happy get` is taken as `args.all`

**Comment by TechWiz-3** [comment]
Personally the way I would do this is (after adding the commands to argparse):

1. Add two more optional arguments to `read_file()`. Pass in the argument after `until` or `before`
2. Put an if statement for each in `read_file()`
3. Loop through the file using the time regex provided in line `84`
4. Open the file and loop through each entry
5. [Compare](https://stackoverflow.com/questions/8142364/how-to-compare-two-dates) provided date with the date. Depending on the result, break or keep going

Don't worry about support for the `--flowers` option initially, that can be figured out after the commands are working 👍

**Comment by diwash007** [comment]
Please assign this issue to me :P

**Comment by TechWiz-3** [comment]
Yezzir
