### ISSUE TITLE
Print help command if no subcommand is used

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/happy-jar-cli#44]
If no subcommand is used, print the help message and exit

**Comment by Kd-Here** [comment]
Hello TechWiz can I help you with this PR.
I had good exp in python.
After a some research I can implement this codition for terminal.

**Comment by TechWiz-3** [comment]
Perfect, let me know if you need any help 👍

**Comment by Kd-Here** [comment]
**Thanks Tech wiz for assigning task.
Im a beginner to CLI coding can you help  me where should i try.**


I am reffering this blog will it help?
[Real python CLI guide](https://realpython.com/command-line-interfaces-python-argparse/#:~:text=The%20command%20line%20interface%20(also,currently%20the%20Python%20argparse%20library)


_Till now I successfully learned how to setup happy cli in my device_
![image](https://user-images.githubusercontent.com/90677747/201584682-5f27369c-ba6d-4c9b-9901-9bf6d56b4db5.png)

**Comment by TechWiz-3** [comment]
Yeah for sure, that's a good blog 👍

**Comment by TechWiz-3** [comment]
Currently, what happens if you just run `poetry run happy`?

The old behavior was that nothing happened and it just exited, so in your new version it should print the `happy -h` help message. This can be done with [`print_help()`](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.print_help)

**Comment by Kd-Here** [comment]
Thanks for explaining it to me.
I am testing it now.
I am checking poetry document hope I find the solution

**Comment by TechWiz-3** [comment]
Poetry documentation? Have you been following the development info in the `CONTRIBUTING.md`? That contains everything you need to know about using poetry for the project. Happy-Jar uses `argparse` to parse command line arguments, so the documentation i linked above for `print_help()` is `argparse` documentation.

https://github.com/TechWiz-3/happy-jar-cli/blob/main/CONTRIBUTING.md#development-info
