### ISSUE TITLE
Add support for markdown emojis

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/happy-jar-cli#5]
Use `Textualize/rich` to print emojis in entries with the `:emoji:` format.

https://rich.readthedocs.io/en/stable/markup.html#emoji

**Comment by micahyoung324** [comment]
Hello, can I take this issue, please?

**Comment by TechWiz-3** [comment]
Certainly 👍

**Comment by TechWiz-3** [comment]
Any updates? @mxw7265

**Comment by micahyoung324** [comment]
Sorry I was busy with stuffs. I just created pull request. I hope that's good! Thanks!
